# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://alpha.rarus-crimea.ru/api/client/select/telephone/79784658647
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
###
GET http://alpha.rarus-crimea.ru/api/client/select/card/0000000000000001
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6

###
GET http://alpha.rarus-crimea.ru/api/client/select
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
GET http://alpha.rarus-crimea.ru/api/client/select-active
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
POST http://alpha.rarus-crimea.ru/api/client/select-by-days
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="firstday"

2019-04-01
--WebAppBoundary--
Content-Disposition: form-data; name="lastday"

2019-04-30
--WebAppBoundary--
###
POST http://alpha.rarus-crimea.ru/api/client/select-by-days
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="firstday"

test
--WebAppBoundary--
Content-Disposition: form-data; name="lastday"

2019-04-30
--WebAppBoundary--
###

POST http://alpha.rarus-crimea.ru/api/client/create
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="lastname"

Чекалов
--WebAppBoundary--
--WebAppBoundary
Content-Disposition: form-data; name="firstname"

Сергей
--WebAppBoundary--
Content-Disposition: form-data; name="telephone"

79783604326
--WebAppBoundary--
Content-Disposition: form-data; name="birthday"

1957-05-08
--WebAppBoundary--
Content-Disposition: form-data; name="code"

0000000000000007
--WebAppBoundary--
Content-Disposition: form-data; name="bonus"

0
--WebAppBoundary--
Content-Disposition: form-data; name="discount"

0
--WebAppBoundary--

###
POST http://alpha.rarus-crimea.ru/api/client/update/3
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="lastname"

Польский
--WebAppBoundary--
--WebAppBoundary
Content-Disposition: form-data; name="firstname"

Артем
--WebAppBoundary--
Content-Disposition: form-data; name="telephone"

79783643435
--WebAppBoundary--
Content-Disposition: form-data; name="birthday"

1957-05-08
--WebAppBoundary--
Content-Disposition: form-data; name="code"

0000000000000003
--WebAppBoundary--
Content-Disposition: form-data; name="bonus"

567
--WebAppBoundary--
Content-Disposition: form-data; name="discount"

0
--WebAppBoundary--
Content-Disposition: form-data; name="mode"

bonus
--WebAppBoundary--
Content-Disposition: form-data; name="status"

active
--WebAppBoundary--
Content-Disposition: form-data; name="edition"

2019-04-03
--WebAppBoundary--
###

GET http://alpha.rarus-crimea.ru/api/client/delete/13
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6

###

GET http://alpha.rarus-crimea.ru/api/client/3/block-card
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6

###
GET http://alpha.rarus-crimea.ru/api/client/3/delete-card
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
###

GET http://alpha.rarus-crimea.ru/api/client/3/test
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
###
