# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://alpha.rarus-crimea.ru/api/client/select
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
###
GET http://alpha.rarus-crimea.ru/api/client/select
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
###
GET http://alpha.rarus-crimea.ru/api/client/select
Authorization: Basic NjQzNTliNzE5Mjc0NGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
###