# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://alpha.rarus-crimea.ru/api/login
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
GET http://alpha.rarus-crimea.ru/api/user/select
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
GET http://alpha.rarus-crimea.ru/api/user/select/1
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
POST http://alpha.rarus-crimea.ru/api/user/create
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name_user"

Ветров Иван
--WebAppBoundary--
Content-Disposition: form-data; name="function"

operator
--WebAppBoundary--

###
POST http://alpha.rarus-crimea.ru/api/user/update/3
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="api_key"

c46b66891e3c4e57c2a19d7c24b2c31573f90ed0a8c356ef
--WebAppBoundary--
Content-Disposition: form-data; name="name_user"

Ветров Иван
--WebAppBoundary--
Content-Disposition: form-data; name="function"

manager
--WebAppBoundary--

###
GET http://alpha.rarus-crimea.ru/api/user/delete/3
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###




