# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://stud03/api/client/1/bonus/select
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6

###
POST http://stud03/api/client/1/bonus/select-by-days
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="firstday"

2019-04-01
--WebAppBoundary--
Content-Disposition: form-data; name="lastday"

2019-04-30
--WebAppBoundary--
###
POST http://stud03/api/client/1/bonus/add
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="amount"

5234
--WebAppBoundary--
Content-Disposition: form-data; name="border"

1000
--WebAppBoundary--
Content-Disposition: form-data; name="balance"

43
--WebAppBoundary--
Content-Disposition: form-data; name="date_bonus"

2019-03-02 11:16:12
--WebAppBoundary--

###
POST http://stud03/api/client/1/bonus/add
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="amount"

5234
--WebAppBoundary--
Content-Disposition: form-data; name="border"

1000
--WebAppBoundary--
Content-Disposition: form-data; name="balance"

43
--WebAppBoundary--
Content-Disposition: form-data; name="date_bonus"

2019-04-21 11:16:12
--WebAppBoundary--

###
POST http://stud03/api/client/3/bonus/add
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="amount"

5234
--WebAppBoundary--
Content-Disposition: form-data; name="border"

1000
--WebAppBoundary--
Content-Disposition: form-data; name="balance"

43
--WebAppBoundary--

###
POST http://stud03/api/client/1/bonus/update/4
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="balance"

43
--WebAppBoundary--
Content-Disposition: form-data; name="status"

deleted
--WebAppBoundary--
Content-Disposition: form-data; name="date_bonus"

2019-03-02 11:16:12
--WebAppBoundary--

###
GET http://stud03/api/client/1/bonus/delete/4
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6

###
GET http://stud03/api/bonus/select
Authorization: Basic NjQzNTliNzE5Mjc0NmExNDc0MGFkNGJiN2FmZTRlMDk3MzI3ZDA3OTAxOTBmZDE2MzE6

###
POST http://stud03/api/client/1/bonus/remove
Authorization: Basic MTQ2YTc0OTI3MTliMzU2NDA5NGVmZTdhYmJkNDBhNzQxNmZkOTAwMTc5ZDAyNzczNTQ6
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="remove_bonus"

4672
--WebAppBoundary--

###
