# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://stud03/api/client/2/discount/select

###
POST http://stud03/api/client/2/discount/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="current"

5
--WebAppBoundary--
Content-Disposition: form-data; name="new"

10
--WebAppBoundary--
Content-Disposition: form-data; name="date_discount"

2019-03-02 11:16:12
--WebAppBoundary--

###
POST http://stud03/api/client/2/discount/update/2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="current"

10
--WebAppBoundary--
Content-Disposition: form-data; name="new"

5
--WebAppBoundary--
Content-Disposition: form-data; name="date_discount"

2019-03-02 11:16:12
--WebAppBoundary--

###
GET http://stud03/api/client/2/discount/delete/2

###
GET  http://stud03/api/discount/select

###